### ISSUE TITLE
Sent emails are not saved in "Sent" folder (in Gmail client)

### ISSUE THREAD

**Issue by vssenko** [wildbit/postmark.js#103]
Sent emails are not saved in "Sent" folder (in Gmail client)
Do I need to add some flags when using this package?
Or it's a matter of postmark setup itself?

postmark version: 2.8.1

Thanks in advance

**Comment by ibalosh** [comment]
Hi @vssenko 

please send details to our support team https://postmarkapp.com/contact . 
That issue is not related to the library.

Igor
