### ISSUE TITLE
License: MITNFA or MIT?

### ISSUE THREAD

**Issue by franciscolourenco** [wildbit/postmark.js#104]
Hi everyone, the [LICENSE](https://github.com/wildbit/postmark.js/blob/master/LICENSE) file says MIT, but package.json says ` 
`MITNFA`. 

This is causing problems with our automated license checker. Could you please clarify which one of the licenses this library is licensed under?

Thanks!

**Comment by ibalosh** [comment]
Hi @franciscolourenco 

oh, thats a mistake in package.json, will see to update it. The license is MIT
