### ISSUE TITLE
Provide a Promise-ified API.

### ISSUE THREAD

**Issue by atheken** [wildbit/postmark.js#13]
In order to better support `async/await` support that is coming in newer versions of Node.js, provide a "promisified" implementation client methods. Consider using `bluebird` to provide this functionality.

**Comment by sambs** [comment]
See: https://github.com/wildbit/postmark.js/pull/17

**Comment by atheken** [comment]
Version 1.4.0 now returns promises when you omit a callback from client method invocations.
