### ISSUE TITLE
Warning: a promise was rejected with a non-error: [object Object]

### ISSUE THREAD

**Issue by kimmobrunfeldt** [wildbit/postmark.js#16]
I'm promisifying `sendEmailWithTemplate` method as advised in this issue comment: https://github.com/wildbit/postmark.js/issues/5#issuecomment-262687667.

However postmark library is not sending standard Error objects, which is the usual node convention. Bluebird outputs this warning because it expects all rejections to be rejected with `new Error()` object.

The code where normal JS object is passed to callback instead of an Error object is here:
https://github.com/wildbit/postmark.js/blob/1e12e27586fd7b3ed863360903be2dd926939891/lib/postmark/clientDefaults.js#L72

**Comment by kimmobrunfeldt** [comment]
I'm using this as a workaround:

```js

**Comment by atheken** [comment]
@kimmobrunfeldt Hi there. In `1.4.0`, we've added Promise support. To get a promise back, do not include a callback, just call client methods, and without it, and they will return Promises which you can add continuations to.

**Comment by DevBrent** [comment]
Continuing this thread, there is a thrown string in Client.js that should definitely be an error. We took the route @kimmobrunfeldt took and wrapped all error responses from the library to make them actual errors.

https://github.com/wildbit/postmark.js/issues/20
