### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by benbayard** [wildbit/postmark.js#18]
Keeping the typescript types and the actual code in sync can be difficult, but the power it gives developers for development and safety is huge.

**Comment by atheken** [comment]
We'd actually like to move the whole library to using Typescript.

A huge help would be to transliterate the models from the .net library to Typescript classes. The models that need converted are here:

https://github.com/wildbit/postmark-dotnet/tree/master/src/Postmark/Model &
https://github.com/wildbit/postmark-dotnet/tree/master/src/Postmark.PCL/Model

@benbayard Are you interested in contributing this code?

**Comment by benbayard** [comment]
Hey @atheken I actually made TS typings for `@types/postmark`, so moving that code here should not be too difficult: 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/postmark/index.d.ts

**Comment by atheken** [comment]
That is a good start, but for version 2, I'd like to actually port the code to using Typescript throughout. This has some benefits of assisting in development and testing of the module, and no need to keep .d.ts files in sync with the actual JS.

Thanks for publishing that to DT.

**Comment by benbayard** [comment]
Absolutely, that's what I meant! I can try to convert this later on this weekend.

**Comment by swftvsn** [comment]
I don't have access to Visual Studio, but it seems the conversion can be [automated](https://visualstudiomagazine.com/articles/2016/05/16/typescript-class-with-csharp.aspx )

Are there any timeline when typescript conversion might happen?

**Comment by swftvsn** [comment]
Any news about this? @atheken

**Comment by atheken** [comment]
We are in the process of finalizing a brand new edition of postmark.js that is re-written in typescript.

https://github.com/wildbit/postmark.js/tree/typescript-support2

Feel free to reference this branch in your project to give it a test drive. I would expect it to land in master and be released in the next week.

**Comment by swftvsn** [comment]
Awesome! Thanks @atheken !

**Comment by ibalosh** [comment]
we just released new version of library with added Typescript support
