### ISSUE TITLE
Sending a template email with attachment

### ISSUE THREAD

**Issue by dooburt** [wildbit/postmark.js#2]
I'd like to be able to send a templated email with attachment, but can find no documentation on how to do this.  I've done plenty of stabbing around and some aborted attempts too.  I found the 'emailWithTemplate' method reference in another comment, but that has no attachments method.

Is it possible to help a lost dev out and send me on my way please?

Thanks!

p.s. great product btw despite this little bump in the road here...

**Comment by dooburt** [comment]
I solved this. The mistake was I was doing the v1.0.0 instantiation and not v1.2.1:-

`var postmark = require('postmark');
var client = new postmark.client('key');
client.emailWithTemplate({"TemplateId": 88888, "TemplateModel": {}});`

Issue resolved.

**Comment by atheken** [comment]
Hmm, There really should be no difference. All versions should support instantiating a new client using the "legacy" method:

```javascript
var client = require('postmark')('key')
```

Of course, the client itself didn't have template support until v1.2.0 -- At any rate, glad this is solved for you. Please feel free to contact Postmark Support if you have further questions.
