### ISSUE TITLE
Do not throw strings or return error callbacks with type object.

### ISSUE THREAD

**Issue by DevBrent** [wildbit/postmark.js#20]
Line 23 of Client.js: ```throw ("You must provide your postmark API key");```

Line 73 of ClientDefaults.js: ```callback({
                  status: response.statusCode,
                  message: data['Message'],
                  code: data['ErrorCode']
                });```

In real application frameworks, this makes dealing with your library a huge pita by multiple measures. It's really easy to return an Error instance with custom properties or create your own Error which will be broadly supported by any library working with this dependency.

The primary complaint is about throwing strings. A string is not an error.

**Comment by atheken** [comment]
@DevBrent Thanks for the recommendation. This is good feedback, and I guess it just hadn't occurred to me to normalize those since they're really coming from different sources. Let me give it a little bit of thought and we'll do some work to improve this.

**Comment by DevBrent** [comment]
Thanks! We were chasing a strange issue in a fresh development environment in which we were trying to minimize the number of required API keys it used. It's the only client library for third-party services that had us lost for a little while trying to figure out what was wrong.

https://eslint.org/docs/rules/no-throw-literal
> It is considered good practice to only throw the Error object itself or an object using the Error object as base objects for user-defined exceptions. The fundamental benefit of Error objects is that they automatically keep track of where they were built and originated.
