### ISSUE TITLE
send batch using template

### ISSUE THREAD

**Issue by foundAhandle** [wildbit/postmark.js#26]
How do I send a batch of emails using a template?

**Comment by atheken** [comment]
We don't *currently* have a batch send endpoint in the Postmark API.

For now, the best way to do it is to iterate over each message you want to send and send it to the `emailWithTemplate` method.

**Comment by ibalosh** [comment]
Hi @foundAhandle 

you can use now `sendEmailBatchWithTemplates` endpoint to send a batch of emails using a template.
