### ISSUE TITLE
Consistent errors

### ISSUE THREAD

**Issue by erfanio** [wildbit/postmark.js#30]
It would be nice to have more consistent errors from the client.
At the moment an error could be an Error object or it could be just a simple object with `{ status, message, code }`.

This makes it difficult to work with the errors the client returns. If you want errors with a status code maybe you should have a look at [Boom](https://github.com/hapijs/boom), the objects Boom returns are proper errors but also preserve the HTTP information.

**Comment by ibalosh** [comment]
We added custom errors model to version 2.0.0 of library which supports now this
