### ISSUE TITLE
Installation fails on node 10.10

### ISSUE THREAD

**Issue by qrohlf** [wildbit/postmark.js#33]
**system:** macOS High Sierra 10.13.6
**node version:** v10.10.0
**yarn version:** 1.9.4

When trying to install Postmark in my development environment, the install fails with the following message:

```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
```

It looks like one of your dependencies needs to be updated in order to support node 10. I'm going to skip integrating Postmark into my app for now, but I may come back to this next week and hit you with a PR if it's as simple as version-bumping one of your deps.

<img width="640" alt="screen shot 2018-09-16 at 11 48 15 am" src="https://user-images.githubusercontent.com/347189/45599768-6b420a80-b9a6-11e8-93f6-1418d4b210b0.png">

**Comment by ibalosh** [comment]
Hi @qrohlf 

thank you for reporting this. We are doing a major update of the library, with typescript support. All of the dependencies and the code are being completely refactored.

It is going to be released in couple of weeks (hopefully next week).

We can check out the error then.

**Comment by qrohlf** [comment]
Got it. This is a blocking issue for me using your platform, would you be
open to a PR if I’m able to find a dep bump that solves this issue?

**Comment by qrohlf** [comment]
Removing my lock file did indeed fix my issue! Thanks for the help, should have done more searching before filing an issue.

**Comment by ibalosh** [comment]
Hey!

no worries, glad things got sorted out and it works 

Igor
