### ISSUE TITLE
2.0.0 types - expose supporting types also

### ISSUE THREAD

**Issue by swftvsn** [wildbit/postmark.js#34]
Hi,

we have a service, that enables passing attachments as a parameter and we'd like to use the type from this library, but it seems that `Attachment` from SupportingTypes.d.ts is not exposed, so we can't declare

```ts
import * as postmark from 'postmark'

const userCertificateAttachment: postmark.Models.Attachment = { ... }
```

Which would make it easier to divide logic. For now we've copied the type, but really would like for it to be visible.

Thank you for the awesome work in 2.0!

**Comment by atheken** [comment]
We'll update the lib and export this today. Based on your feedback, we will probably also make some other adjustments to types/module structure, stay tuned.
