### ISSUE TITLE
2.0.0 Preferred way to refer to types

### ISSUE THREAD

**Issue by swftvsn** [wildbit/postmark.js#35]
Hi!

Would you recommend to import types like this:

```ts
import * as postmark from 'postmark'
const postmarkClient = new postmark.ServerClient('secretysecret')
```

or like this?:

```ts
import { ServerClient } from 'postmark'
const postmarkClient = new ServerClient('secretysecret')
```

Note that I can't import 
```ts
import { MessageSendingResponse } from 'postmark'
```

But rather I have to 
```ts
import { Models } from 'postmark'
...
const response: ModelsMessageSendingResponse = ....
```
Which feels a bit clumsy.

Thank you for the awesome work in 2.0!

**Comment by atheken** [comment]
@ibalosh and I struggled a bit with how to export the types while we were building out this update.

To your first question, about whether use the wildcard for imports or destructuring it, I think it's personal preference.

Personally, I prefer destructuring the import as it reduces repeating the namespace in the code.

Part of the reason the models are in a separate namespace is to create some separation between the "important" classes (ServerClient, AccountClient, Callback<T>), and all the supporting models. But it does feel a bit clumsy. We'll review this again, and make revisions as necessary.

Also note that we tried to define classes for any object that we expect a user of the library to instantiate (making it easier to provide required parameters, and take advantage of type inference.), and we used interfaces for any results from API responses (these would never be directly instantiated by a consumer of this client).

And you're very welcome for the 2.0 update. We have wanted to move to TypeScript and get the benefits of having the type system in place for a long time, so I'm happy to see you're excited to use it.

**Comment by atheken** [comment]
We have released 2.1 this morning, which addresses some of these issues. Given how important the common classes of `Message`, `Attachment`, `Headers`, `TemplatedMessage` are, these are now exported at the top-level of the module, so that should simplify the common sending case.

For more consistency and better intellisense, we also modified a few of the filter parameter type definitions, which is technically a breaking change from 2.0, but given that 2.0 is < 24 hours old, we feel this is better than bumping it a major version in this case.

**Comment by swftvsn** [comment]
Thanks for the super quick response time!

It's a lot better to use now, there's only one minor inconsistency that I found out:
```ts
declare type TemplatedMessage = Models.TemplateMessage;
```
depending where you import from,  the same model is either Template**d**Message or TemplateMessage. (Note the 'd' on the first form.)

After that minor nag, I think we can close this one.

**Comment by ibalosh** [comment]
Hi,

we fixed that inconsistency too in the latest version 2.2.0
