### ISSUE TITLE
How to migrate from 1.x to 2.x

### ISSUE THREAD

**Issue by joostdebruijn** [wildbit/postmark.js#36]
It might be a lack of my search and reading skills, but I cannot find documentation on how to migrate from 1.x to 2.x. Or are there no breaking changes?

**Comment by ibalosh** [comment]
Hey @joostdebruijn 

the move from version 1 to 2 was big, and you are right, we should have documented that better. 

The biggest change is in terms of retrieving server and account clients.

``` javascript
const serverToken = "xxxx-xxxxx-xxxx-xxxxx-xxxxxx"
let postmark = require("postmark")
let client = new postmark.ServerClient(serverToken);
```

``` javascript
let postmark = require("postmark")
const accountToken = "xxxx-xxxxx-xxxx-xxxxx-xxxxxx"
let accountClient = new postmark.AccountClient(accountToken);
```

methods for endpoints work very similarly to what you are used to.

I have added meanwhile today detailed [wiki](https://github.com/wildbit/postmark.js/wiki) examples to help out the move.

I will see to get there today a detailed example on how to migrate too.

Let me know if that helps?

**Comment by joostdebruijn** [comment]
Hey @ibalosh, thanks for the quick response! The documentation is much better now.

**Comment by ibalosh** [comment]
hey! 

You are welcome, glad it helped out. We will improve it bit more during next couple of days
