### ISSUE TITLE
Non Typescript documentation

### ISSUE THREAD

**Issue by kelkes** [wildbit/postmark.js#38]
Any chance we can get a documentation without the whole typescript stuff? Lots of devs are not using typescript (for good reasons). Lib documentation is completely useless right now :( That's not even a documentation.

**Comment by ibalosh** [comment]
Hi @kelkes 

non typescript version works pretty much the same as typescript one minus the types. However, I do understand typescript docs can be confusing.

To make that bit simpler, I was about to add more detailed examples to our wiki page, which should help using the library for non typescript projects.

I just updated our wiki with [code examples](https://github.com/wildbit/postmark.js/wiki) for most of the library.

Check it out and let me know how it goes.

**Comment by kelkes** [comment]
The new code examples are helping a lot! Thanks for that. More usage documentation is great, I can dig my way thru typescript documentation but auto-generated class docs are not very helpful in terms of... where to start, how to do that, etc. Even when using Typescript in my own project.

So again 👍  for more code examples :)

**Comment by ibalosh** [comment]
Hey!

I agree completely, I am big fan of documentation with examples. Helps you move faster, and dig into more detailed specs as you go.

Glad they help!
