### ISSUE TITLE
Crash when unknown error occurs

### ISSUE THREAD

**Issue by kelkes** [wildbit/postmark.js#40]
When an UnkownError occurs (BaseClient => processHttpRequest => generateError => buildStatusError, default fallback) it looks like the error object hast no body property therefore the following error happens. This leads to the problem that the underlying error is hidden.

```
TypeError: Cannot read property 'Message' of undefined
--
  | at ErrorHandler.buildStatusError (/app/node_modules/postmark/dist/client/ErrorHandler.js:54:59)
  | at ErrorHandler.generateError (/app/node_modules/postmark/dist/client/ErrorHandler.js:20:25)
  | at /app/node_modules/postmark/dist/client/BaseClient.js:79:38
  | at process._tickCallback (internal/process/next_tick.js:68:7)
```

I would like to provide a PR but the project is written in Typescript.

**Comment by ibalosh** [comment]
Thanks for reporting this @kelkes . I will check it out in following days

Igor

**Comment by ibalosh** [comment]
Hey @kelkes 

before we dive into checking the issue, could you share any details on when this issue happens when you are using the library? 

Any small piece of code / steps to reproduce it would be great

thx!

**Comment by ibalosh** [comment]
I will probably check it out today, 
ah already seeing the place where the issue can be

Igor

**Comment by ibalosh** [comment]
Hi @kelkes 

I pushed a small release 2.2.2 which should address the issue. Let me know if by any chance you continue to see it.

Igor
