### ISSUE TITLE
Sending email after post request gives ETIMEDOUT

### ISSUE THREAD

**Issue by benjam1n** [wildbit/postmark.js#43]
Hi there! Any ideas why is this happening? It's not all the time but way too often.

```js
Error:  { PostmarkError: ETIMEDOUT
    at ErrorHandler.module.exports.ErrorHandler.buildError (/var/task/user/index.js:51719:16)
    at ErrorHandler.module.exports.ErrorHandler.generateError (/var/task/user/index.js:51708:25)
    at /var/task/user/index.js:19117:38
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) statusCode: 0, code: 0, name: 'PostmarkError' }
```

Here's the code I'm using:

```js
const express = require('express');
const port = process.env.PORT || 3000
const app = express();
const bodyParser = require('body-parser');
const postmark = require("postmark");
const client = new postmark.ServerClient(process.env.POSTMARK);
var jsonParser = bodyParser.json()

app.post('/', jsonParser, function (request, response) {
    let submission = request.body.submission;
    console.log("Sending email to " + submission.email);
    client.sendEmailWithTemplate({
        "From": "hello@example.com",
        "To": submission.email,
        "TemplateAlias": "contact_form",
        "TemplateModel": {
            "name": submission.name
        }
    })
    .then(res => {
        console.log("Email sent at " + res.SubmittedAt);
    })
    .catch(error => console.log('Error: ', error));
    response.end()
});

app.listen(port, err => {
    if (err) throw err
})

```

**Comment by ibalosh** [comment]
Hi @benjam1n 

hm, general PostmarkError by library is thrown when there is no regular response from Postmark. 
From what I could see, timeout is happening when trying to connect to Postmark to send email by Template as you mentioned.

Some things that could be checked:

- How often does the send call run?
- Wondering if network connection on your side is stable on that server? How often do you get the error? 
- Can you run the postmark client outside of express route and see how it behaves then?
- Wondering if you could do a call like ping test , to check connection from your machine to api.postmarkapp.com (call in shell would look like: ping api.postmarkapp.com)

These are the first things to check. We haven't seen yet any issues from customers related to timeout and sending, so these are the routes we think issue could be at.

Igor

**Comment by ibalosh** [comment]
Hi @benjam1n 

also try to experiment with timeout for the sake of test. For client the default is 30 seconds.
This call should increase it to 60: client.clientOptions.timeout=60

Igor

**Comment by benjam1n** [comment]
@ibalosh Thanks for the ideas! It seems everything is alright when `client.sendEmailWithTemplate` is called outside the `app.post`. Changing timeout didn't help.

**Comment by ibalosh** [comment]
oh, glad to hear that!

hm, interesting, wondering why the usual promise format you used first did not work
