### ISSUE TITLE
Promise is not rejected for batch send email call with errors

### ISSUE THREAD

**Issue by heckfordraj** [wildbit/postmark.js#44]
Hi, I've got a bit of a problem when using the library to send an email using the `sendEmailBatchWithTemplates` function.

When sending an invalid batch email the promise still resolves, because the error handler is only checking the status code:

https://github.com/wildbit/postmark.js/blob/cb334f475bb1de76cc51cc68dcad0b67874daaf2/src/client/BaseClient.ts#L162-L164

I've had a chat with the support team, and they said that for all the batch email api calls, the status code will always return 200, so you have to check for an `ErrorCode` value in the body of the response

I could try and make a PR, but it's probably going to be a breaking change

**Comment by atheken** [comment]
Hi there. Generally, our libraries defer to the API to propagate information and errors. While I understand that the preference here would be to get a non-OK http-level response if any messages in the batch aren't accepted, this would be a breaking change in our API. 

We will improve the documentation for the batch calls in this library, as well as our developer docs to make it more clear that the results should be checked, even when the request itself succeeds, but we are not going to change the semantics for the batch endpoints at this time.
