### ISSUE TITLE
[documentation-wiki] What is the difference between using tags, metadata and custom headers?

### ISSUE THREAD

**Issue by fredguth** [wildbit/postmark.js#45]
I want to send a reply to a previously received message with some kind of code that I can track in the next time I receive a message from this thread. 

I was thinking about changing the message header and was looking for how to do it in the documentation. 

Then I saw you have tags, metadata and custom headers and I am wondering what are the differences, the pros and cons of each option?

**Comment by atheken** [comment]
Good question!

Generally, tags are good to group general classes of messages (“welcome email”, “password reset”, etc.), and aggregating stays/searching events based on those tags.

Custom metadata is similar, but is more useful for labeling individual messages with uniquely identifying information, such as a userid. Like tags, this information is included in message details endpoints and webhook payloads. This allows you to correlate these payloads with records in your system without recording the corresponding “messageid” during sending. However, you cannot aggregate stats in Postmark using custom metadata. Custom metadata is not included within the headers of outgoing messages, so your recipients would never see this as headers in their message.

Custom Headers are not searchable within Postmark, and are generally used to convey special information to receiving mail systems if they read/trust them. The use case for Custom Headers generally is a special type of integration with a destination mail server and aren’t generally useful when sending to common public mailbox providers like gmail, yahoo, etc.

If you still have more questions for your specific use case, feel free to contact support and we’ll do our best to answer.

**Comment by fredguth** [comment]
Just one point, though.  If I understood correctly, tags nor metadata are sent with the message.  So, if I need to insert some kind of "thread id" to classify all messages from the same thread, I will need to change my reply-to or insert the metadata it in the body?  is that right?  I don't get why can't I keep the metadata public and send to other recipients for later processing.  

I don't like the solution of changing the email in reply-to because the recipients will see this strange hash as an email address instead of a simple one.

**Comment by rianvdm** [comment]
You're correct that the metadata is not included in the email content, so recipients will not see the data you add. This is by design so there is no risk of exposing sensitive data to customers.

However, when a message is returned via the Messages API, the metadata you added will be returned with it. The metadata you added will also be included when you receive a webhook related to the message. If, for example, you get a delivery or bounce webhook, you’d be able to match that back with any custom identifiers you have on your end.

Would the API or webhook solution work for you?

**Comment by fredguth** [comment]
Sorry, I still don't understand if a ReplyTo my message, which I understand is a different MessageID, will bring the metadata. I guess not.  How to add some kind of metadata in an email thread so that I can check it next time a message from the same thread arrives?

**Comment by atheken** [comment]
Hi Fred, this conversation is more related to how email works in general, and not something specific to this repo. If you contact support (reference this github issue, if you wish), we can better answer questions for your specific use case.

Just generally: Yes, you can look at message headers on inbound messages and they will **sometimes** include `In-Reply-To`, or `References` headers -- though, these are **not guaranteed** to be included in all replies by all senders. If you are using Inbound processing from postmark, a more reliable way to handle this is to set your reply-to address to some thread-specific value. Again, if you contact Postmark Support directly we can probably help you with more specific information.
