### ISSUE TITLE
docs directory is quite big around 30Mb

### ISSUE THREAD

**Issue by j1348** [wildbit/postmark.js#48]
I had added the postmark dependencies in my project, and I think that this is not relevant to embed the docs directory in the npm package.

Thank you for your understanding.

**Comment by ibalosh** [comment]
hi @j1348 

thats a good point. We will consider this in next update of the library.

**Comment by j1348** [comment]
Yes. Thx.

**Comment by leeoniya** [comment]
also, please consider replacing `request` with `node-fetch`.

https://packagephobia.now.sh/result?p=request
https://packagephobia.now.sh/result?p=node-fetch

**Comment by j1348** [comment]
> hi @j1348
> 
> thats a good point. We will consider this in next update of the library.

I think you can even push a minor fix. This will save bandwidth and time.

**Comment by ibalosh** [comment]
Hey @j1348 m @leeoniya 

we have released couple of minutes ago a new version without the docs. 
We will consider `request` library update in future versions too. However, that update is more involved, touching the core behaviour of the library and affects everything.

Igor
