### ISSUE TITLE
PostmarkError: ETIMEOUT & ServiceUnavailablerError

### ISSUE THREAD

**Issue by tbell511** [wildbit/postmark.js#53]
Hi Postmark!

I've been using the Node Client (v2.2.0) for sometime now and have had zero problems until today.  My production server has logged 4 errors in the course of about 30minutes that all originate from Postmark.  I am attaching images of all the info I have. 

<img width="823" alt="Screen Shot 2019-07-03 at 11 52 25 AM" src="https://user-images.githubusercontent.com/25237806/60606352-32ceba00-9d89-11e9-84b8-392d250bdd53.png">

Let me know if you need any more info.  Thanks.

**Comment by tbell511** [comment]
![screencapture-sentry-io-share-issue-e402d20069564443a7c8137aeb0d62ff-2019-07-03-11_55_43](https://user-images.githubusercontent.com/25237806/60606724-df10a080-9d89-11e9-8610-157997ad1912.png)

**Comment by tbell511** [comment]
![screencapture-sentry-io-share-issue-dbbd75969b4045139ee54d16bd504e03-2019-07-03-11_56_57](https://user-images.githubusercontent.com/25237806/60606790-f8195180-9d89-11e9-9428-f287e247ab88.png)

**Comment by rianvdm** [comment]
@tbell511 We've had some service issues today, which this is likely related to. Are you still seeing these issues? https://status.postmarkapp.com/incidents/7626

**Comment by tbell511** [comment]
No issues since the initial four.  Looks like everything is resolved.  Thanks!
