### ISSUE TITLE
Cannot set content-type header

### ISSUE THREAD

**Issue by powerc9000** [wildbit/postmark.js#57]
I want to be able to send an invite with an email. When you are sending an iCalendar invite the `Content-Type` header should be `text/calendar`. I get the error 
```{ ErrorCode: 300, Message: 'Header \'Content-Type\' not allowed.' }```

I do not want to send the invite as an attachment because it will not render the action buttons in most email providers. (However it does show up as a calendar invite as an attachment).

Is there anything to be done?

**Comment by rianvdm** [comment]
We have a known issue (not specifically related to this library) with processing inline text/calendar content types. This is something that's on our radar and we need to address, but I unfortunately don't have a specific timeline for you. I added your details to our tracking system though, so we'll let you know once we start working on it.

**Comment by powerc9000** [comment]
Thanks. I figured out how to properly attach the ics file so that is shows the RSVP button. I can write that all up in a comment if you'd like to use it for future reference. Otherwise this is no longer an issue on my end.

**Comment by ibalosh** [comment]
Hey @powerc9000 

we are glad you found a solution. 
If you can write up in comment how you did it, that would be great!
Thanks!

Igor
