### ISSUE TITLE
Sending is not supported on the supplied 'MessageStream'.

### ISSUE THREAD

**Issue by tgensol** [wildbit/postmark.js#58]
Hi there,

Since this morning, I am getting that error : 

> Sending is not supported on the supplied 'MessageStream'.

But I did not change anything on my server or my code. It happens on some emails that I am forwarding,

What this error means ?

Thanks

**Comment by atheken** [comment]
Hi @tgensol - can you contact support about this case with a code snippet showing how you're using the library? We'd like to understand the circumstances under which this can happen, as the postmark.js library has been tested for this and works as expected. Please feel free to link to this issue when you contact support.

**Comment by tgensol** [comment]
I removed MessageStream, in the payload of the emails, and it is working well. But it looks like that property of inbound email was added recently
