### ISSUE TITLE
npm request deprecated

### ISSUE THREAD

**Issue by lvnilesh** [wildbit/postmark.js#59]
request has been deprecated, see https://github.com/request/request/issues/3142

Please update dependencies.

Thanks.

**Comment by ibalosh** [comment]
Hi 

thank you for letting us know. We will see to do that in near future.

Igor

**Comment by swftvsn** [comment]
Hi,

if no fancy stuff is needed, maybe google's `teeny-request` is enough?https://github.com/googleapis/teeny-request (apache-2 license)

retries can be added using https://github.com/stephenplusplus/retry-request (MIT license)
`@google-cloud/common` depends on both, so I don't think those are going anywhere soon.

The only real downside is that the lib does not support promises, so it's all callback hell.

**Comment by lvnilesh** [comment]
https://github.com/wildbit/postmark.js/pull/60 Thank you.

**Comment by ibalosh** [comment]
You are welcome, we have released the update
