### ISSUE TITLE
MessageSendingReponse.MessageID should be optional or nullable

### ISSUE THREAD

**Issue by eugene-kim** [wildbit/postmark.js#65]
Hello,

Shouldn't `MessageSendingReponse.MessageID` be optional or nullable to handle the case where there's an error with `ServerClient.sendEmail`?

```typescript
export interface MessageSendingResponse extends DefaultResponse {
    To?: string;
    Cc?: string;
    Bcc?: string;
    SubmittedAt: string;
    MessageID: string;
}
```

**Comment by ibalosh** [comment]
Hi,

thank you for the report. We have made MessageID optional in latest version 2.5.6

**Comment by eugene-kim** [comment]
Thank you @ibalosh !
