### ISSUE TITLE
How do we create a message stream?

### ISSUE THREAD

**Issue by jineshshah36** [wildbit/postmark.js#66]
I see the message stream API reference (https://postmarkapp.com/developer/api/message-streams-api#create-a-message-stream), but I'm struggling to figure out how to create it using the SDK. Is this something that has not yet been released?

**Comment by ibalosh** [comment]
Hi @jineshshah36 

you are right, this is not released yet. I will see to release the update it this week

**Comment by ibalosh** [comment]
@jineshshah36 message stream endpoints are released in newest 2.6.0 version couple of minutes ago

https://github.com/wildbit/postmark.js/wiki/Message-Streams
