### ISSUE TITLE
Documentation for creating webhooks is missing `MessageStream`

### ISSUE THREAD

**Issue by courthead** [wildbit/postmark.js#69]
`serverClient.createWebhook` allows you to pass a `MessageStream` key in the object, in addition to `Url` and `Triggers`. However, the documentation and the wiki don't specify this.

**Comment by ibalosh** [comment]
Hi @courthead 

could you share more details? 

I don't see `MessageStream` as a parameter for create in [Postmark developer docs](https://postmarkapp.com/developer/api/webhooks-api), neither in create [webhook request model](https://github.com/wildbit/postmark.js/blob/master/src/client/models/webhooks/Webhook.ts). It is available only when listing webhooks. I am wondering if we missed something in the logic of the API.

**Comment by courthead** [comment]
You can see it here in the docs: https://postmarkapp.com/developer/api/webhooks-api#create-a-webhook

**Comment by ibalosh** [comment]
Got it, thank you, will see to resolve that today

**Comment by ibalosh** [comment]
In latest version 2.6.1 released today, we have added MessageStream to typescript model and updated documentation.
