### ISSUE TITLE
Use behind a proxy

### ISSUE THREAD

**Issue by resteinbock** [wildbit/postmark.js#7]
What configuration do I need to do for the Postmark npm module work behind a proxy in node.js?

I see that the `requestFactory` uses the node `http` and `https` libraries to make API calls to api.postmarkapp.com, but I do not see any options to provide settings for making calls behind a proxy.

Additionally, I do not see methods to properly make calls behind a proxy...

**Comment by atheken** [comment]
Thanks for opening the issue, will follow up in the PR: https://github.com/wildbit/postmark.js/pull/8
