### ISSUE TITLE
Upgrade to axios 0.21.1 to resolve critical security vulnerability

### ISSUE THREAD

**Issue by adilsoncarvalho** [wildbit/postmark.js#72]
Postmark currently uses `axios@0.19.2`, and it has a critical security vulnerability that only got fixed on `axios@0.21.1`.

```
warning postmark > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
```

I opened https://github.com/wildbit/postmark.js/pull/71 to bump axio's version to the one free of that critical security vulnerability.

**Comment by olaven** [comment]
Came here to post the same as @adilsoncarvalho. Google Cloud automatically prevents deployments because of this dependency.

**Comment by ibalosh** [comment]
Hi

thank you for reporting this, we will see to do the update soon

Igor

**Comment by ibalosh** [comment]
Hi
we resolved an updated version couple of minutes ago, version 2.7.0

**Comment by olaven** [comment]
Wonderful! @ibalosh
