### ISSUE TITLE
CreateMessageStreamRequest model not aligned with API documentation

### ISSUE THREAD

**Issue by c-eliasson** [wildbit/postmark.js#78]
We are using the library to create broadcast messages streams with custom unsubscribe handling. 

The API documentation specify that `UnsubscribeHandlingType` can be set when creating a new message stream: https://postmarkapp.com/developer/api/message-streams-api#create-a-message-stream

The `CreateMessageStreamRequest` model does not define that property however, as [seen here](https://github.com/wildbit/postmark.js/blob/759ffd376d09744840d9e12c0b76ddf63e2b9867/src/client/models/streams/MessageStream.ts#L52) - causing a TypeScript error when trying to set `UnsubscribeHandlingType` through the library.

Temporary workaround is to just `// @ts-ignore` the line, but it seems like the library is lagging behind on this endpoint.

**Comment by ibalosh** [comment]
Hi @c-eliasson 

thank you for letting us know about the issue. I will see to update the library by end of the week the latest.

Igor

**Comment by ibalosh** [comment]
Updated [wiki](https://github.com/wildbit/postmark.js/wiki/Message-Streams) examples with additional fields, and released a version 2.7.3 which supports them
