### ISSUE TITLE
`InboundDomain` missing on `UpdateServerRequest`

### ISSUE THREAD

**Issue by klaemo** [wildbit/postmark.js#79]
Hey there,
I noticed a tiny issue with the type definitions.

`InboundDomain` is missing on `UpdateServerRequest`. It is correctly sent to the API though if I set it.

I guess the fix is as simple as adding it to https://github.com/wildbit/postmark.js/blob/master/src/client/models/server/Server.ts#L27?

I can submit a PR if you like!

Thanks

**Comment by ibalosh** [comment]
hi @klaemo 

thank you for letting us know. We have updated the model in the 2.7.4 version of the library.

**Comment by klaemo** [comment]
Thank you 🙏
