### ISSUE TITLE
Make docs searchable

### ISSUE THREAD

**Issue by tyrw** [wildbit/postmark.js#84]
In visiting the docs at https://wildbit.github.io/postmark.js/index.html, there was no way for me to find a method I already knew the name of: `sendEmailWithTemplate`

Searching the page through the browser's functionality yields no results. I had to resort to googling for it, and picking the ~fifth result.

**Comment by ibalosh** [comment]
Hi @tyrw 

Thank you for reporting this as a feature. Unfortunately docs page is generated by typedoc and pushed to Github, so search is out of our control. We will keep this in mind though for future updates.
