### ISSUE TITLE
Get inactive addresses from ServerClient.sendEmail response

### ISSUE THREAD

**Issue by nikhilag** [wildbit/postmark.js#87]
This is with reference to an issue with response when I try to send email via `ServerClient.sendEmail()` method. Currently it seems your response gives inactive email ids only as part of the string message in response. A sample response for this case is:-
```
{
  "MessageID": "...",
  "To": "email1,email2",
  "SubmittedAt": "2021-12-22T12:52:08.9541898Z",
  "Message": "Message OK, but will not deliver to these inactive addresses: email1",
  "ErrorCode": 0
}
```

Now the problem is that I can only figure out that email didn't go to `email1` by extracting it from the `Message` string which is not a reliable approach. And there is no webhook triggered to track this kind of failure either.

My suggestion would be that in such a case, the response could return an `inactiveAddresses` string array with all email ids that failed. Kindly make it easier to extract the failed email ids in any better way.

**Comment by ibalosh** [comment]
Thank you for suggestion @nikhilag 

we will consider it in following releases.

**Comment by ibalosh** [comment]
Hi @nikhilag 

we have made an update which should make this easier to manage. Update will return specific error if all email addresses are inactive with parsed recipients and we allow you to use a parser in case some recipients are inactive.

Sharing a code sample of how this looks like:

```
import * as postmark from "./index";
const client = new postmark.ServerClient("123456-123456"); 


client.sendEmail({
  From: 'from@example.com', 
  To: 'to@example.com, bounce@example.com', 
  HtmlBody: "test body", 
  Subject: "subject"
}).then(result => {
  const recipients = postmark.Errors.InactiveRecipientsError.parseInactiveRecipients(result.Message);
  console.log(recipients);
}).catch( (error:postmark.Errors.InactiveRecipientsError) => {
  console.error('Error recipients:', error.recipients);
})
```

In case when all recipients are inactive we throw specific error which has recipients parsed. In case when some recipients are inactive, we are keeping the response as minimal and consistent for all users and therefore it matches our API. In that case  we recommend using parser shown above to get inactive recipients.
