### ISSUE TITLE
ContentLength property missing from Attachment type

### ISSUE THREAD

**Issue by andrewblaney** [wildbit/postmark.js#90]
In multiple [inbound email webhook](https://postmarkapp.com/developer/webhooks/inbound-webhook) responses from postmark, we see the `ContentLength: number` property, but this is missing from[ the Attachment type defined in SupportingTypes](https://github.com/wildbit/postmark.js/blob/master/src/client/models/message/SupportingTypes.ts#L34-L45), is this intentional? We'd like to use it, but can't access it through `Models.InboundMessageDetails`

```json
{
   "Content": "data",
   "ContentLength": 66,
   "Name": "scratch_14.json",
   "ContentType": "application/json",
   "ContentID": "f_kyd9930n0"
}
```
thanks!

**Comment by ibalosh** [comment]
Hi 

we have released version 2.8.2 which resolves this issue
