### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Powersource** [wildbit/postmark.js#95]
There are two previous issues on this

https://github.com/wildbit/postmark.js/issues/76
https://github.com/wildbit/postmark.js/issues/67

but it wasn't really fixed there even if they're closed.

I guess I want a clearer error message when the token is missing.

**Comment by ibalosh** [comment]
Thanks for reporting this issue, we will see to provide clearer message

**Comment by ibalosh** [comment]
Hi @Powersource 

we have fixed this in version 2.9.0 we have just released.

**Comment by Powersource** [comment]
Thank you for the quick fix!
